const prodacts = [
        
        //***************************************************************************************************************
    // {id:1,
    //     img: '<img src="./img/catalog_img/catalog/sets/photo_2021-08-20_11-07-10.jpg" alt="macarron">',
    //     name: 'Набор "С 1 сентября! Любимая учительница"',
    //     text: '16 штук в коробке. Вкусы: фисташка, вишня, шоколад, кокос.',
    //     cost: '1300',},
    // {id:2,
    //     img: '<img src="./img/catalog_img/catalog/sets/dsc_1242-2048x1870.jpg" alt="macarron">',
    //     name: 'Набор "С Днём Знаний! Любимая учительница"',
    //     text: '40 штук в коробке. Вкусы: фисташка, вишня, шоколад, кокос.',
    //     cost: '3900',},
    // {id:3,
    //      img: '<img src="./img/catalog_img/catalog/sets/dsc_1220-scaled.jpg" alt="macarron">',
    //      name: 'Набор "С 1 сентября! Увлекательных открытий"',
    //     text: '16 штук в коробке. Вкусы: фисташка, вишня, шоколад, кокос.',
    //      cost: '133',},
    // {id:4,
    //     img: '<img src="./img/catalog_img/catalog/sets/dsc_1217-scaled.jpg" alt="macarron">',
    //     name: 'Набор "С 1 сентября! Новых достижений"',
    //     text: '16 штук в коробке. Вкусы: фисташка, вишня, шоколад, кокос.',
    //     cost: '1300',},
        // {id:5,
        //     img: '<img src="./img/catalog_img/catalog/sets/dsc_1209-scaled.jpg" alt="macarron">',
        //     name: 'Набор "С 1 сентября! Успешной учёбы"',
        //     text: '9 штук в коробке. Вкусы: фисташка, вишня, шоколад',
        //     cost: '750',},
        // {id:6,
        //     img: '<img src="./img/catalog_img/catalog/sets/dsc_1212-scaled.jpg" alt="macarron">',
        //     name: 'Набор "С 1 сентября! Отличных оценок"',
        //     text: '9 штук в коробке. Вкусы: фисташка, вишня, шоколад',
        //     cost: '750',},
        {id:7,
             img: '<img src="./img/catalog_img/catalog/sets/s-dnyom-rojdeniya-3.png" alt="macarron">',
             name: 'Набор "День рождения"',
            text: '16 штук в коробке. Вкусы: фисташка, вишня, кокос, шоколад',
             cost: '1300',},
        {id:8,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-k-chayu-6.png" alt="macarron">',
            name: '15 макаронс в прозрачной коробке',
            text: '15 штук в коробке. Вкусы: фисташка, шоколад-апельсин, клубника-базилик, эрл-грей, малина, трюфель.',
            cost: '900',},
        {id:9,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-k-chayu-5.png" alt="macarron">',
            name: 'Набор в закрытой коробке на 6 штук',
            text: '6 штук в коробке. Вкусы: шоколад-банан, лимон, эрл-грей, облепиха-розмарин, малина, лаванда.',
            cost: '350',},
        {id:10,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-k-chayu-2.png" alt="macarron">',
            name: 'Набор в закрытой коробке на 24 штуки',
            text: '24 штуки в коробке. Вкусы: лимон, шоколад-банан, фисташка, шоколад-апельсин, облепиха-розмарин, клубника-базилик, смородина, кокос, манго-маракуйя, лаванда, эрл-грей, малина.',
            cost: '1400',},
        {id:11,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-6.png" alt="macarron">',
            name: 'Набор в прозрачной коробке Вдохновение',
            text: '7 штук в коробке. Вкусы: лимон, шоколад-банан, фисташка, шоколад-апельсин, облепиха-розмарин, клубника-базилик, смородина.',
            cost: '420',},
        {id:12,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-1.png" alt="macarron">',
            name: 'Набор в прозрачной коробке Великолепная 7',
            text: '7 штук в коробке. Вкусы: фисташка, лаванда, шоколад-банан, манго-маракуйя, клубника-базилик, малина, смородина.',
            cost: '420',},
        {id:13,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-2.png" alt="macarron">',
            name: 'Набор в прозрачной коробке Сладкоежка',
            text: '5 штук в коробке. Вкусы: лимон, шоколад-банан, манго-маракуйя, клубника-базилик, смородина.',
            cost: '320',},
        {id:14,
            img: '<img src="./img/catalog_img/catalog/sets/macarons.png" alt="macarron">',
            name: 'Набор в прозрачной коробке Эстет',
            text: '5 штук в коробке. Вкусы: эрл-грей, голубой сыр, трюфель, лаванда, кокос.',
            cost: '320',},
        {id:15,
            img: '<img src="./img/catalog_img/catalog/sets/new-year.png" alt="macarron">',
            name: 'Набор к Новому году',
            text: '16 штук в коробке. Вкусы: фисташка, вишня, шоколад, кокос',
            cost: '1300',},
        {id:16,
            img: '<img src="./img/catalog_img/catalog/sets/new-year-2.png" alt="macarron">',
            name: 'Набор-мини New Year',
            text: '9 штук в коробке. Вкусы: фисташка, вишня, шоколад',
            cost: '750',},
        {id:17,
            img: '<img src="./img/catalog_img/catalog/sets/new-year-4.png" alt="macarron">',
            name: 'Набор-мини к Новому году',
            text: '9 штук в коробке. Вкусы: фисташка, вишня, шоколад',
            cost: '750',},
        {id:18,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-3.png" alt="macarron">',
            name: 'Набор-мини ко дню свадьбы',
            text: '9 штук в коробке. Вкусы: фисташка, вишня, шоколад',
            cost: '750',},
        {id:19,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-13.png" alt="macarron">',
            name: 'Бонбоньерки на свадьбу',
            text: '3 макаронс в наборе. Вкусы на выбор',
            cost: '240',},
        {id:20,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-9.png" alt="macarron">',
            name: 'Бонбоньерки с именами гостей',
            text: 'Вкусы на выбор',
            cost: '85',},
        {id:21,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-18.png" alt="macarron">',
            name: 'Бонбоньерки для гостей',
            text: '2 макаронс в коробочке. Вкусы на выбор',
            cost: '200',},
        {id:22,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-14.png" alt="macarron">',
            name: 'Пирамидка из макаронс, 14 этажей',
            text: '350 макаронс в наборе. Вкусы: фисташка, клубника-базилик, кокос, пармезан, чёрный трюфель, солёная карамель, сникерс, вишня, шоколад-банан, голубой сыр, ананас, облепиха-розмарин, малина, эрл грей, лаванда, песто, смородина, манго-маракуйя',
            cost: '21000',},
        {id:23,
            img: '<img src="./img/catalog_img/catalog/sets/macarons-na-svadbu-16.png" alt="macarron">',
            name: 'Пирамидка из макаронс, 10 этажей',
            text: '240 макаронс в наборе. Вкусы: фисташка, клубника-базилик, кокос, пармезан, чёрный трюфель, солёная карамель, сникерс, вишня, шоколад-банан, голубой сыр, ананас, облепиха-розмарин',
            cost: '14400',},
        {id:24,
            img: '<img src="./img/catalog_img/catalog/sets/uchitel-5.png" alt="macarron">',
            name: 'Набор-мини ко дню воспитателя',
            text: '9 штук в коробке. Вкусы: фисташка, вишня, шоколад',
            cost: '750',},
        {id:25,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-7.png" alt="ekler">',
            name: 'Ванильный эклер',
            text: 'Безумно вкусные эклеры изготовлены только из натуральных ингредиентов, без химии и консервантов!',
            cost: '99',},
        {id:26,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-13.png" alt="ekler">',
            name: 'Клубничный эклер',
            text: 'Безумно вкусные эклеры изготовлены только из натуральных ингредиентов, без химии и консервантов!',
            cost: '99',},
        {id:27,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-10.png" alt="ekler">',
            name: 'Малиновый эклер',
            text: 'Безумно вкусные эклеры изготовлены только из натуральных ингредиентов, без химии и консервантов!',
            cost: '99',},
        {id:28,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-1.png" alt="ekler">',
            name: 'Шоколадный эклер',
            text: 'Безумно вкусные эклеры изготовлены только из натуральных ингредиентов, без химии и консервантов!',
            cost: '99',},
        {id:29,
            img: '<img src="./img/catalog_img/catalog/ecler/ekler.png" alt="ekler">',
            name: 'Эклер с карамелью',
            text: 'Безумно вкусные эклеры изготовлены только из натуральных ингредиентов, без химии и консервантов!',
            cost: '99',},
        {id:30,
            img: '<img src="./img/catalog_img/catalog/ecler/kupit-ekler-spb-17.png" alt="ekler">',
            name: 'Набор из 6 эклеров',
            text: '6 вкусов в наборе: ванильный, смородиновый, клубничный, малиновый, карамельный, шоколадный',
            cost: '600',},
        // ************************************************************************************
    {id:31,
            img: '<img src="./img/catalog_img/catalog/vafle_pipes/trubochki-4.png" alt="trubochki">',
            name: 'Набор трубочек со сгущёнкой',
            text: 'В составе наших вафель — натуральное масло и яйца. Мы не используем яичный желток и сухие порошки, не используем консерванты, разрыхлители и загустители. В составе начинки: натуральная сгущёнка, масло и молоко.',
            cost: '900',},
    {id:32,
            img: '<img src="./img/catalog_img/catalog/vafle_pipes/trubochki-3.png" alt="trubochki">',
            name: 'Трубочка со сгущёнкой',
            text: 'В составе наших вафель — натуральное масло и яйца. Мы не используем яичный желток и сухие порошки, не используем консерванты, разрыхлители и загустители. В составе начинки: натуральная сгущёнка, масло и молоко.',
            cost: '95',},
    //**********************************************************************************************
    {id:33,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitroli_macaronshop.png" alt="profitroli">',
            name: 'BIG-профитроли',
            text: '40 штук в коробке. Вкусы: абрикос, карамель, шоколад, малина, крем-брюле',
            cost: '2000',},
    {id:34,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitroli_kupit.png" alt="profitroli">',
            name: 'Великолепные «15»',
            text: '15 штук в коробке. Вкусы: абрикос, малина, крем-брюле, шоколад, карамель',
            cost: '450',},
    {id:35,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitroli-4.png" alt="profitroli">',
            name: 'Профитроли мини с малиной',
            text: '9 штук в коробке. Вкусы: малина, карамель',
            cost: '330',},
    {id:36,
            img: '<img src="./img/catalog_img/catalog/profitroly/profitrili-mini.png" alt="profitroli">',
            name: 'Профитроли мини с шоколадом',
            text: '9 штук в коробке. Вкусы: шоколад, карамель',
            cost: '330',},
            
            
]




// перевести цены!